# Make sure to edit this file within src/cfg/travis.yml to ensure that your modifications are not overwritten by the build.

sudo: true
language: java
jdk:
  - openjdk7

before_script:
  - mkdir dist
  - mkdir workspace
  - mkdir workspace/AppEngineSDK
  - cd workspace/AppEngineSDK
  - travis_retry wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.22.zip; unzip appengine-java-sdk-1.9.22.zip
  - cd ../..
  - export ANT_OPTS=-javaagent:$HOME/build/LucidTechnics/faery/workspace/AppEngineSDK/appengine-java-sdk-1.9.22/lib/agent/appengine-agent.jar
  - export AIRLIFT_APP_ENGINE_HOME=$HOME/build/LucidTechnics/faery/workspace/AppEngineSDK/appengine-java-sdk-1.9.22
  - ant -Dairlift.env=desktop runserver &
  - npm install -g phantomjs
  - npm install -g karma
  - npm install -g karma-phantomjs-launcher
  - npm install -g bower
  - npm install -g karma-jasmine --save-dev
  - npm install -g karma-coverage --save-dev
  - npm install -g karma-junit-reporter --save-dev
  - npm install -g karma-chrome-launcher --save-dev
  - npm install -g karma-firefox-launcher --save-dev
  - bower install
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable

# whitelist
branches:
  only:
    - master
    - ci
    - qa
    - test
    - dev

notifications:
  email:
    - ci@lucidtechnics.com
  slack: lucidtechnics:7nW8OF9uwyiQcj1R0PKXKeSF
